// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "PP同学",
            "email": "710955321@qq.com"
        },
        "license": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/visitor/create": {
            "post": {
                "description": "输入信息来创建一个visitor",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Visitor接口"
                ],
                "summary": "新增visitor用户",
                "parameters": [
                    {
                        "description": "注册访客信息",
                        "name": "visitor",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.CreateVisitorVO"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "注册成功",
                        "schema": {
                            "$ref": "#/definitions/entity.ResponseObject"
                        }
                    },
                    "403": {
                        "description": "用户名重复",
                        "schema": {
                            "$ref": "#/definitions/entity.ResponseObject"
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "$ref": "#/definitions/entity.ResponseObject"
                        }
                    }
                }
            }
        },
        "/v1/visitor/delete/{id}": {
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "输入Visitor_id以删除visitor",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Visitor接口"
                ],
                "summary": "删除某个visitor",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "删除的visitor id参数",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "删除成功"
                    },
                    "400": {
                        "description": "输入参数有误",
                        "schema": {
                            "$ref": "#/definitions/entity.ResponseObject"
                        }
                    },
                    "402": {
                        "description": "用户未授权",
                        "schema": {
                            "$ref": "#/definitions/entity.ResponseObject"
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "$ref": "#/definitions/entity.ResponseObject"
                        }
                    }
                }
            }
        },
        "/v1/visitor/detail/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "在URL中输入ID以获取Visitor信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Visitor接口"
                ],
                "summary": "获取单个visitor的信息（以id获取）",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "所请求的id参数",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "查询成功",
                        "schema": {
                            "$ref": "#/definitions/model.Visitor"
                        }
                    },
                    "400": {
                        "description": "输入参数有误",
                        "schema": {
                            "$ref": "#/definitions/entity.ResponseObject"
                        }
                    },
                    "402": {
                        "description": "用户未授权",
                        "schema": {
                            "$ref": "#/definitions/entity.ResponseObject"
                        }
                    },
                    "404": {
                        "description": "未找到资源",
                        "schema": {
                            "$ref": "#/definitions/entity.ResponseObject"
                        }
                    }
                }
            }
        },
        "/v1/visitor/flip/{id}": {
            "patch": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Flip某个visitor的状态，1-\u003e0;0-\u003e1",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Visitor接口"
                ],
                "summary": "禁用(启用)某个visitor",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "禁用的visitor id参数",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "禁用成功",
                        "schema": {
                            "$ref": "#/definitions/entity.ResponseObject"
                        }
                    },
                    "400": {
                        "description": "输入参数有误",
                        "schema": {
                            "$ref": "#/definitions/entity.ResponseObject"
                        }
                    },
                    "402": {
                        "description": "用户未授权",
                        "schema": {
                            "$ref": "#/definitions/entity.ResponseObject"
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "$ref": "#/definitions/entity.ResponseObject"
                        }
                    }
                }
            }
        },
        "/v1/visitor/list": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "在URL中输入pageNum, pageSize以拉取Visitor列表信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Visitor接口"
                ],
                "summary": "获取多个visitor的信息",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "请求的页表大小",
                        "name": "pageSize",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "请求的offset",
                        "name": "pageNum",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "查询成功",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Visitor"
                            }
                        }
                    },
                    "400": {
                        "description": "输入参数有误",
                        "schema": {
                            "$ref": "#/definitions/entity.ResponseObject"
                        }
                    },
                    "402": {
                        "description": "用户未授权",
                        "schema": {
                            "$ref": "#/definitions/entity.ResponseObject"
                        }
                    },
                    "404": {
                        "description": "未找到资源",
                        "schema": {
                            "$ref": "#/definitions/entity.ResponseObject"
                        }
                    }
                }
            }
        },
        "/v1/visitor/login": {
            "post": {
                "description": "输入用户名密码以登录",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "登录接口"
                ],
                "summary": "visitor登录",
                "parameters": [
                    {
                        "description": "访客登录信息（只需要填写nickname、password）",
                        "name": "visitor",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.VisitorLoginVo"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "登录成功",
                        "schema": {
                            "$ref": "#/definitions/entity.ResponseObject"
                        }
                    },
                    "403": {
                        "description": "用户名或密码错误",
                        "schema": {
                            "$ref": "#/definitions/entity.ResponseObject"
                        }
                    },
                    "404": {
                        "description": "未找到该用户",
                        "schema": {
                            "$ref": "#/definitions/entity.ResponseObject"
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "$ref": "#/definitions/entity.ResponseObject"
                        }
                    }
                }
            }
        },
        "/v1/visitor/modify/{id}": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "输入新的Visitor信息以更新信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Visitor接口"
                ],
                "summary": "修改visitor信息",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "修改的visitor id参数",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "访客信息",
                        "name": "visitor",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.CreateVisitorVO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "修改成功",
                        "schema": {
                            "$ref": "#/definitions/entity.ResponseObject"
                        }
                    },
                    "402": {
                        "description": "用户未授权",
                        "schema": {
                            "$ref": "#/definitions/entity.ResponseObject"
                        }
                    },
                    "403": {
                        "description": "用户名重复",
                        "schema": {
                            "$ref": "#/definitions/entity.ResponseObject"
                        }
                    },
                    "404": {
                        "description": "未找到资源",
                        "schema": {
                            "$ref": "#/definitions/entity.ResponseObject"
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "$ref": "#/definitions/entity.ResponseObject"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "entity.ResponseObject": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "业务响应码（非HTTP码）"
                },
                "message": {
                    "type": "string",
                    "example": "Some message about the code."
                }
            }
        },
        "model.CreateVisitorVO": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "xxxxx@xx.com"
                },
                "mobile": {
                    "type": "string",
                    "example": "13xxxxxxxxx"
                },
                "nickname": {
                    "type": "string",
                    "example": "PP同学"
                },
                "password": {
                    "type": "string",
                    "example": "123456"
                }
            }
        },
        "model.Visitor": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "xxxxx@xx.com"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "lastLoginTime": {
                    "type": "string",
                    "example": "2020-08-02T21:20:41+08:00"
                },
                "mobile": {
                    "type": "string",
                    "example": "13xxxxxxxxx"
                },
                "nickname": {
                    "type": "string",
                    "example": "PP同学"
                },
                "password": {
                    "type": "string",
                    "example": "123456"
                },
                "registerTime": {
                    "type": "string",
                    "example": "2020-08-02T21:20:41+08:00"
                },
                "status": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "model.VisitorLoginVo": {
            "type": "object",
            "properties": {
                "nickname": {
                    "type": "string",
                    "example": "PP同学"
                },
                "password": {
                    "type": "string",
                    "example": "123456"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "0.1",
	Host:        "",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "PP同学个人博客接口文档",
	Description: "MarvelousBlog-Backend Swagger接口文档",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
