definitions:
  entity.ResponseBody:
    properties:
      code:
        type: integer
      message:
        example: Some message about the code.
        type: string
    type: object
  model.Visitor:
    properties:
      email:
        example: xxxxx@xx.com
        type: string
      id:
        example: 1
        type: integer
      lastLoginTime:
        example: "2020-08-02T21:20:41+08:00"
        type: string
      mobile:
        example: 13xxxxxxxxx
        type: string
      nickname:
        example: PP同学
        type: string
      password:
        example: "123456"
        type: string
      registerTime:
        example: "2020-08-02T21:20:41+08:00"
        type: string
      status:
        example: 1
        type: integer
    type: object
host: localhost:8600
info:
  contact:
    email: 710955321@qq.com
    name: PP同学
  description: MarvelousBlog-Backend Swagger接口文档
  license: {}
  title: PP同学个人博客接口文档
  version: "0.1"
paths:
  /v1/visitor/create:
    post:
      consumes:
      - application/json
      description: 输入信息来创建一个visitor
      parameters:
      - description: 访客电话号码
        in: body
        name: mobile
        schema:
          type: string
      - description: 访客邮箱
        in: body
        name: email
        schema:
          type: string
      - description: 访客昵称
        in: body
        name: nickname
        required: true
        schema:
          type: string
      - description: 访客密码
        in: body
        name: password
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/entity.ResponseBody'
      summary: 新增visitor用户
      tags:
      - Visitor接口
  /v1/visitor/info/{id}:
    get:
      consumes:
      - application/json
      description: 在URL中输入ID以获取Visitor信息
      parameters:
      - description: 所请求的id参数
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Visitor'
      summary: 获取单个visitor的信息（以id获取）
      tags:
      - Visitor接口
swagger: "2.0"
