definitions:
  entity.ResponseObject:
    properties:
      code:
        example: 业务响应码（非HTTP码）
        type: string
      message:
        example: Some message about the code.
        type: string
    type: object
  model.Article:
    properties:
      authorId:
        type: integer
      content:
        type: string
      id:
        type: integer
      labelId:
        type: integer
      lastModifyTime:
        type: string
      postTime:
        type: string
      status:
        type: integer
      summary:
        type: string
      title:
        type: string
      visitCount:
        type: integer
    type: object
  model.Comment:
    properties:
      articleId:
        example: 1
        type: integer
      content:
        example: 写得不错！
        type: string
      email:
        example: 1846156416@qq.com
        type: string
      mobile:
        example: 137xxxxxxxx
        type: string
    type: object
  model.Label:
    properties:
      description:
        example: 如何使用Gin框架搭建一个web服务器
        type: string
      id:
        example: 1
        type: integer
      labeName:
        example: Gin框架
        type: string
    type: object
  model.LoginVo:
    properties:
      nickname:
        example: PP同学
        type: string
      password:
        example: "123456"
        type: string
    type: object
info:
  contact:
    email: 710955321@qq.com
    name: PP同学
  description: MarvelousBlog-Backend Swagger接口文档
  license: {}
  title: PP同学接口文档
  version: "0.1"
paths:
  /v1/article/create:
    post:
      consumes:
      - application/json
      description: 创建一篇新的文章
      parameters:
      - description: 文章内容
        in: body
        name: label
        required: true
        schema:
          $ref: '#/definitions/model.Article'
      produces:
      - application/json
      responses:
        "201":
          description: 新增文章成功
          schema:
            $ref: '#/definitions/entity.ResponseObject'
        "500":
          description: 服务器错误
          schema:
            $ref: '#/definitions/entity.ResponseObject'
      security:
      - ApiKeyAuth: []
      summary: 新增文章
      tags:
      - Article接口
  /v1/article/delete/{id}:
    delete:
      consumes:
      - application/json
      description: 输入文章id以删除文章（软删除，并未在数据库中实际删除）
      parameters:
      - description: 删除的article的id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: 删除成功
        "400":
          description: 输入参数有误
          schema:
            $ref: '#/definitions/entity.ResponseObject'
        "402":
          description: 用户未授权
          schema:
            $ref: '#/definitions/entity.ResponseObject'
        "500":
          description: 服务器错误
          schema:
            $ref: '#/definitions/entity.ResponseObject'
      security:
      - ApiKeyAuth: []
      summary: 删除某篇文章
      tags:
      - Article接口
  /v1/article/detail/{id}:
    get:
      consumes:
      - application/json
      description: 获取某篇文章的内容
      parameters:
      - description: 所请求的文章id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 查询成功
          schema:
            items:
              $ref: '#/definitions/model.Article'
            type: array
        "400":
          description: 输入参数有误
          schema:
            $ref: '#/definitions/entity.ResponseObject'
        "404":
          description: 未找到资源
          schema:
            $ref: '#/definitions/entity.ResponseObject'
      summary: 获取某篇文章
      tags:
      - Article接口
  /v1/article/enable/{id}:
    patch:
      consumes:
      - application/json
      description: 管理员重新启用某篇文章（status 0 -> 1）
      parameters:
      - description: enable的文章id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Enable成功
          schema:
            $ref: '#/definitions/entity.ResponseObject'
        "400":
          description: 输入参数有误
          schema:
            $ref: '#/definitions/entity.ResponseObject'
        "404":
          description: 未找到资源
          schema:
            $ref: '#/definitions/entity.ResponseObject'
      security:
      - ApiKeyAuth: []
      summary: 管理员Enable文章
      tags:
      - Article接口
  /v1/article/list:
    get:
      consumes:
      - application/json
      description: 获取某篇文章的内容
      parameters:
      - description: 请求的页码数
        in: query
        name: pageNum
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 查询成功
          schema:
            items:
              $ref: '#/definitions/model.Article'
            type: array
        "400":
          description: 输入参数有误
          schema:
            $ref: '#/definitions/entity.ResponseObject'
        "404":
          description: 未找到资源
          schema:
            $ref: '#/definitions/entity.ResponseObject'
      summary: 分页获取全部文章(每页10篇）
      tags:
      - Article接口
  /v1/article/modify/{id}:
    put:
      consumes:
      - application/json
      description: 输入新的文章内容以更新文章
      parameters:
      - description: 修改的文章的id
        in: path
        name: id
        required: true
        type: integer
      - description: 修改的文章信息
        in: body
        name: visitor
        required: true
        schema:
          $ref: '#/definitions/model.Article'
      produces:
      - application/json
      responses:
        "200":
          description: 修改成功
          schema:
            $ref: '#/definitions/entity.ResponseObject'
        "402":
          description: 用户未授权
          schema:
            $ref: '#/definitions/entity.ResponseObject'
        "404":
          description: 未找到资源
          schema:
            $ref: '#/definitions/entity.ResponseObject'
        "500":
          description: 服务器错误
          schema:
            $ref: '#/definitions/entity.ResponseObject'
      security:
      - ApiKeyAuth: []
      summary: 修改文章内容
      tags:
      - Article接口
  /v1/article/onLabel/{labelId}:
    get:
      consumes:
      - application/json
      description: 获取某一标签下的全部文章
      parameters:
      - description: 请求的标签的id
        in: path
        name: labelId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 查询成功
          schema:
            items:
              $ref: '#/definitions/model.Article'
            type: array
        "400":
          description: 输入参数有误
          schema:
            $ref: '#/definitions/entity.ResponseObject'
        "404":
          description: 未找到资源
          schema:
            $ref: '#/definitions/entity.ResponseObject'
      summary: 获取某一标签下的全部文章
      tags:
      - Article接口
  /v1/article/superAuthor/list:
    get:
      consumes:
      - application/json
      description: 管理员获取全部文章（包括status = 0的）
      parameters:
      - description: 请求的页码数
        in: query
        name: pageNum
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 查询成功
          schema:
            items:
              $ref: '#/definitions/model.Article'
            type: array
        "400":
          description: 输入参数有误
          schema:
            $ref: '#/definitions/entity.ResponseObject'
        "404":
          description: 未找到资源
          schema:
            $ref: '#/definitions/entity.ResponseObject'
      security:
      - ApiKeyAuth: []
      summary: 管理员获取全部文章
      tags:
      - Article接口
  /v1/author/login:
    post:
      consumes:
      - application/json
      description: 输入用户名密码以登录
      parameters:
      - description: 作者登录信息
        in: body
        name: visitor
        required: true
        schema:
          $ref: '#/definitions/model.LoginVo'
      produces:
      - application/json
      responses:
        "200":
          description: 登录成功
          schema:
            $ref: '#/definitions/entity.ResponseObject'
        "403":
          description: 用户名或密码错误
          schema:
            $ref: '#/definitions/entity.ResponseObject'
        "404":
          description: 未找到该用户
          schema:
            $ref: '#/definitions/entity.ResponseObject'
        "500":
          description: 服务器错误
          schema:
            $ref: '#/definitions/entity.ResponseObject'
      summary: author登录
      tags:
      - 登录接口
  /v1/comment/delete/{id}:
    delete:
      consumes:
      - application/json
      description: 输入评论id以删除某条评论
      parameters:
      - description: 删除的评论的id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: 删除成功
        "400":
          description: 输入参数有误
          schema:
            $ref: '#/definitions/entity.ResponseObject'
        "402":
          description: 用户未授权
          schema:
            $ref: '#/definitions/entity.ResponseObject'
        "500":
          description: 服务器错误
          schema:
            $ref: '#/definitions/entity.ResponseObject'
      security:
      - ApiKeyAuth: []
      summary: 删除某条评论
      tags:
      - Comment接口
  /v1/comment/list/{articleId}:
    get:
      consumes:
      - application/json
      description: 获取某篇文章文章的20个评论
      parameters:
      - description: 请求的页码数
        in: query
        name: pageNum
        type: integer
      - description: 评论的article的id
        in: path
        name: articleId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 查询成功
          schema:
            items:
              $ref: '#/definitions/model.Comment'
            type: array
        "400":
          description: 输入参数有误
          schema:
            $ref: '#/definitions/entity.ResponseObject'
        "404":
          description: 未找到资源
          schema:
            $ref: '#/definitions/entity.ResponseObject'
      summary: 分页获取某篇文章下的评论
      tags:
      - Comment接口
  /v1/label/create:
    post:
      consumes:
      - application/json
      description: 输入信息来创建一个标签
      parameters:
      - description: 新建的标签信息
        in: body
        name: label
        required: true
        schema:
          $ref: '#/definitions/model.Label'
      produces:
      - application/json
      responses:
        "201":
          description: 新增标签成功
          schema:
            $ref: '#/definitions/entity.ResponseObject'
        "403":
          description: 标签重复
          schema:
            $ref: '#/definitions/entity.ResponseObject'
        "500":
          description: 服务器错误
          schema:
            $ref: '#/definitions/entity.ResponseObject'
      security:
      - ApiKeyAuth: []
      summary: 新增Label标签
      tags:
      - Label接口
  /v1/label/delete/{id}:
    delete:
      consumes:
      - application/json
      description: 输入label_id以删除标签
      parameters:
      - description: 删除的label的id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: 删除成功
        "400":
          description: 输入参数有误
          schema:
            $ref: '#/definitions/entity.ResponseObject'
        "402":
          description: 用户未授权
          schema:
            $ref: '#/definitions/entity.ResponseObject'
        "500":
          description: 服务器错误
          schema:
            $ref: '#/definitions/entity.ResponseObject'
      security:
      - ApiKeyAuth: []
      summary: 删除某个label
      tags:
      - Label接口
  /v1/label/list:
    get:
      consumes:
      - application/json
      description: 获取全部label
      produces:
      - application/json
      responses:
        "200":
          description: 查询成功
          schema:
            items:
              $ref: '#/definitions/model.Label'
            type: array
        "400":
          description: 输入参数有误
          schema:
            $ref: '#/definitions/entity.ResponseObject'
        "402":
          description: 用户未授权
          schema:
            $ref: '#/definitions/entity.ResponseObject'
        "404":
          description: 未找到资源
          schema:
            $ref: '#/definitions/entity.ResponseObject'
      summary: 获取全部label
      tags:
      - Label接口
  /v1/label/modify/{id}:
    put:
      consumes:
      - application/json
      description: 输入修改的label信息以更新信息
      parameters:
      - description: 修改的label id参数
        in: path
        name: id
        required: true
        type: integer
      - description: 修改的标签信息
        in: body
        name: label
        required: true
        schema:
          $ref: '#/definitions/model.Label'
      produces:
      - application/json
      responses:
        "200":
          description: 修改成功
          schema:
            $ref: '#/definitions/entity.ResponseObject'
        "402":
          description: 用户未授权
          schema:
            $ref: '#/definitions/entity.ResponseObject'
        "403":
          description: Label重复
          schema:
            $ref: '#/definitions/entity.ResponseObject'
        "404":
          description: 未找到资源
          schema:
            $ref: '#/definitions/entity.ResponseObject'
        "500":
          description: 服务器错误
          schema:
            $ref: '#/definitions/entity.ResponseObject'
      security:
      - ApiKeyAuth: []
      summary: 修改label
      tags:
      - Label接口
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
