definitions:
  entity.ResponseObject:
    properties:
      code:
        type: integer
      message:
        example: Some message about the code.
        type: string
    type: object
  model.CreateVisitorVO:
    properties:
      email:
        example: xxxxx@xx.com
        type: string
      mobile:
        example: 13xxxxxxxxx
        type: string
      nickname:
        example: PP同学
        type: string
      password:
        example: "123456"
        type: string
    type: object
  model.Visitor:
    properties:
      email:
        example: xxxxx@xx.com
        type: string
      id:
        example: 1
        type: integer
      lastLoginTime:
        example: "2020-08-02T21:20:41+08:00"
        type: string
      mobile:
        example: 13xxxxxxxxx
        type: string
      nickname:
        example: PP同学
        type: string
      password:
        example: "123456"
        type: string
      registerTime:
        example: "2020-08-02T21:20:41+08:00"
        type: string
      status:
        example: 1
        type: integer
    type: object
host: localhost:8600
info:
  contact:
    email: 710955321@qq.com
    name: PP同学
  description: MarvelousBlog-Backend Swagger接口文档
  license: {}
  title: PP同学个人博客接口文档
  version: "0.1"
paths:
  /v1/visitor/create:
    post:
      consumes:
      - application/json
      description: 输入信息来创建一个visitor
      parameters:
      - description: 注册访客信息
        in: body
        name: visitor
        required: true
        schema:
          $ref: '#/definitions/model.CreateVisitorVO'
      produces:
      - application/json
      responses:
        "201":
          description: 注册成功
          schema:
            $ref: '#/definitions/entity.ResponseObject'
        "403":
          description: 用户名重复
          schema:
            $ref: '#/definitions/entity.ResponseObject'
        "500":
          description: 服务器错误
          schema:
            $ref: '#/definitions/entity.ResponseObject'
      summary: 新增visitor用户
      tags:
      - Visitor接口
  /v1/visitor/detail/{id}:
    get:
      consumes:
      - application/json
      description: 在URL中输入ID以获取Visitor信息
      parameters:
      - description: 所请求的id参数
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 查询成功
          schema:
            $ref: '#/definitions/model.Visitor'
        "400":
          description: 输入参数有误
          schema:
            $ref: '#/definitions/entity.ResponseObject'
        "404":
          description: 未找到资源
          schema:
            $ref: '#/definitions/entity.ResponseObject'
      summary: 获取单个visitor的信息（以id获取）
      tags:
      - Visitor接口
  /v1/visitor/list:
    get:
      consumes:
      - application/json
      description: 在URL中输入ID以获取Visitor信息
      parameters:
      - description: 请求的页表大小
        in: query
        name: pageSize
        type: integer
      - description: 请求的offset
        in: query
        name: pageNum
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 查询成功
          schema:
            items:
              $ref: '#/definitions/model.Visitor'
            type: array
        "400":
          description: 输入参数有误
          schema:
            $ref: '#/definitions/entity.ResponseObject'
        "404":
          description: 未找到资源
          schema:
            $ref: '#/definitions/entity.ResponseObject'
      summary: 获取多个visitor的信息
      tags:
      - Visitor接口
swagger: "2.0"
